/*
 * generated by Xtext
 */
package com.atropos.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class GarfieldUiModule extends com.atropos.ui.AbstractGarfieldUiModule {
	public GarfieldUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
