/*
 * generated by Xtext
 */
package com.atropos;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class GarfieldRuntimeModule extends com.atropos.AbstractGarfieldRuntimeModule {

}
