/*
 * generated by Xtext
 */
package com.atropos.ui.contentassist

import com.atropos.ui.contentassist.AbstractGarfieldProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
class GarfieldProposalProvider extends AbstractGarfieldProposalProvider {
}
